name: Deploy

on:
    pull_request:
        branches:
        - releases/*

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.1.0
      with:
        args: --strict
      
    - name: Build
      run: exec ./.github/scripts/build_app.sh
      
    - name: Run tests
      run: exec ./.github/scripts/test_app.sh
      
    - name: 'Upload app to TestFlight'
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: 'path/to/application.ipa'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
